name: "Deploy to server"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "SSH & Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "SSH"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: '60022'
          script: |
            cd ~/attendify/monitoring
            git pull
            docker compose pull
            chown go-w ./beats/filebeat/conf.yml
            chown go-w ./beats/metricbeat/conf.yml
            docker compose up -d --build
